version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-hello-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15w2qnje7b2rl"
s3_prefix = "sam-app-hello-example"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
